# ~/.config/starship.toml

add_newline = false
command_timeout = 1000
# format = """$os$username$hostname$kubernetes$directory$git_branch$git_status⌦"""
format = """
[](#9A348E)\
$os\
$username\
[](bg:#DA627D fg:#9A348E)\
$directory\
[](fg:#DA627D bg:#FCA17D)\
$git_branch\
$git_status\
[](fg:#FCA17D bg:#86BBD8)\
$java\
$julia\
$nodejs\
[](fg:#86BBD8 bg:#06969A)\
$docker_context\
[](fg:#06969A bg:#33658A)\
$time\
[ ](fg:#33658A)\
$character\
"""

# Drop ugly default prompt characters
# [character]
# success_symbol = ''
# error_symbol = ''
[character]
success_symbol = "[➜](bold green)"
error_symbol = "[✗](bold red)"


# ---

[os]
# format = '[$symbol](bold white) '   
style = "fg:#FFFFFF bg:#9A348E"
disabled = false

[os.symbols]
Alpaquita = " "
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = " 󰨡 "

# ---

# Shows the username
[username]
show_always = true
style_user = "fg:#000000 bg:#9A348E"
style_root = "fg:#000000 bg:#9A348E"
format = '[$user ]($style)'
disabled = false

# Shows the hostname
[hostname]
ssh_only = false
format = 'on [$hostname](bold yellow) '
disabled = false

# Shows current directory
[directory]
style = "fg:#000000 bg:#DA627D"
truncation_length = 1
truncation_symbol = '…/'
home_symbol = '󰋜 ~'
read_only_style = 'fg:#FF0000 bg:#DA627D'
read_only = '  '
format = '[ $path ]($style)[$read_only]($read_only_style)'

# Shows current git branch
[git_branch]
symbol = ""
style = "fg:#000000 bg:#FCA17D"
format = '[ $symbol $branch ]($style)'

[git_status]
ahead = " $count"
behind = " $count"
diverged = " $ahead_count $behind_count"
style = "fg:#000000 bg:#FCA17D"
format = '[$all_status$ahead_behind ]($style)'

# Shows kubernetes context and namespace
[kubernetes]
format = 'via [󱃾 $context\($namespace\)](bold purple) '
disabled = true

# ---

[java]
# symbol = " "
style = "fg:#000000 bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[vagrant]
disabled = true

[docker_context]
disabled = true

[helm]
disabled = true

[python]
disabled = true

[nodejs]
disabled = true

[ruby]
disabled = true

[terraform]
disabled = true